### ISSUE TITLE
Example data output

### ISSUE THREAD

**Issue by guysoft** [beddit/beddit-python-bt#1]
Hey,
I am trying to figure out if beddit is the device to base a project on (something for live DSPDS data), but I can't find example output,
Could you paste here example output of relatime data?

Thanks

**Comment by kdikert** [comment]
Hi,

The Beddit sensor unit provides PCM data as its output. (See https://en.wikipedia.org/wiki/Pulse-code_modulation) The data will essentially be a continuous list of numbers, where each number represents the "reading" of the sensor with 104 Hz intervals. The sensor is essentially a force sensor. So if you exert a physical force on the sensor the "readings" are changing rapidly. Correspondingly, if there is little movements (force) on the sensor the "readings" will barely vary.

**Comment by guysoft** [comment]
@kdikert Hey,
So this became super important today - will this work on beddit 1? or 2? or both?

**Comment by jpaalasm** [comment]
Hi. This library is for Beddit 1 (Beddit Classic) exclusively. Beddit 2 (Beddit 2.0 Smart) and Beddit 3 use a BT LE protocol that is different from Beddit 1.

**Comment by guysoft** [comment]
Working, thanks. My sources are here: https://github.com/Tikkun-olam/angelzzz
